### ISSUE TITLE
Contao 4 Compatibility

### ISSUE THREAD

**Issue by GMTeams** [markocupic/news_infinite_scroll#3]
I've installed this package and it was not working in Contao 4.4. I tried many configuration settings, after lot of time i've seen that there is another repository: [contao-news-infinite-scroll-bundle](https://github.com/markocupic/contao-news-infinite-scroll-bundle)
Maybe you can delete the compatibility for this package in Contao Manager? Thanks.

**Comment by markocupic** [comment]
Das stimmt so nicht!
Schau mal hier:
http://contao44.kletterkader.com/newsliste.html
Contao 4.4

**Comment by markocupic** [comment]
Aha habe erst jetzt gesehen, dass du news_infinite_scroll meintest.
Alles klar. Werde die Kompatibilität anpassen. 
Lg Marko

**Comment by GMTeams** [comment]
Vielen Dank, wollte nur verhindern dass es jemand anderem passiert. Ansonsten klasse Erweiterung, hatte schon länger sowas gesucht, danke dafür!
